pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'jdk-17'
    }

    stages {
        stage('Build') {
            steps {
                
                sh ' cd oorder && mvn clean install'
            }
        }
        
    }

    post {
        always {
            junit 'oorder/target/surefire-reports/*.xml'
            publishCoverage adapters: [jacocoAdapter('**/target/site/jacoco/jacoco.xml')]
        }
    }
}
