pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'jdk-17'
    }

    stages {
        stage('Build') {
            steps {
                
                sh ' cd oorder && mvn clean install -DskipTests'
            }
        }
        stage('jenkins-custom-pipeline') {
            steps {
                sh 'cd jenkins-custom-pipeline && mvn -Dmaven.test.failure.ignore=true test'
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml'
        }
    }
}
